# Generated by Django 2.1 on 2018-08-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AbonentNumber', models.CharField(max_length=12)),
                ('AbonentOrg', models.CharField(max_length=30)),
                ('AbonentOperator', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccLogin', models.CharField(max_length=15)),
                ('AccName', models.CharField(max_length=15)),
                ('AccOrg', models.CharField(max_length=30)),
                ('AccMail', models.CharField(max_length=30)),
                ('AccSubscribe', models.CharField(max_length=12)),
            ],
        ),
    ]
