# Generated by Django 2.1 on 2018-08-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField()),
            ],
        ),
    ]
