# Generated by Django 2.1 on 2018-08-29 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSC', '0002_cellnumbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cellnumbers',
            name='Number',
        ),
        migrations.AddField(
            model_name='cellnumbers',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
